version: '3.8'

services:
  # 1. PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: painamnae-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: painamnae_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - painamnae-net
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: painamnae-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:3000"
    env_file: .env
    volumes:
      - ./backend:/app           
      - /app/node_modules        
    networks:
      - painamnae-net

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: painamnae-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - painamnae-net

volumes:
  postgres_data:

networks:
  painamnae-net:
    driver: bridge

# version: '3.8'

# services:
#   # 1. PostgreSQL
#   db:
#     image: postgres:15-alpine
#     container_name: painamnae-db
#     restart: always
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: painamnae_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - painamnae-net

#   backend:
#     build: ./backend
#     container_name: painamnae-backend
#     restart: always
#     depends_on:
#       - db
#     ports:
#       - "8080:3000"
#     env_file: .env  
#     networks:
#       - painamnae-net

#   frontend:
#     build: ./frontend
#     container_name: painamnae-frontend
#     restart: always
#     depends_on:
#       - backend
#     ports:
#       - "3000:3000"
#     env_file: .env  
#     networks:
#       - painamnae-net


# volumes:
#   postgres_data:

# networks:
#   painamnae-net:
#     driver: bridge
